App\Entity\User:
  properties:
    firstName:
      - NotNull: ~
      - Length:
          min: 1
          max: 30
      
    lastName:
      - NotNull: ~
      - Length:
          min: 1
          max: 30

    email:
      - NotNull: ~
      - Email:
          message: The email "{{ value }}" is not a valid email.
