todo_get_all:
  path: api/todos
  methods: GET
  controller: App\Controller\TodoController::index

todo_get_by_id:
  path: api/todos/{id}
  methods: GET
  controller: App\Controller\TodoController::get_by_id

todo_create:
  path: api/todos
  controller: App\Controller\TodoController::create  
  methods: POST

todo_update_by_id :
  path: api/todos/{id}
  methods: PUT
  controller: App\Controller\TodoController::update_by_id
