getAll:
  path: api/todos
  methods: GET
  controller: App\Controller\TodoController::getAll

getById:
  path: api/todos/{id}
  methods: GET
  controller: App\Controller\TodoController::getById

create:
  path: api/todos
  controller: App\Controller\TodoController::create  
  methods: POST

updateById :
  path: api/todos/{id}
  methods: PUT
  controller: App\Controller\TodoController::updateById

toggleIsCompleted:
  path: api/todos/{id}
  methods: PATCH
  controller: App\Controller\TodoController::toggleIsCompleted

removeById:
  path: api/todos/{id}
  methods: DELETE
  controller: App\Controller\TodoController::removeById
