todo_getAll:
  path: api/todos
  methods: GET
  controller: App\Controller\TodoController::getAll

todo_getById:
  path: api/todos/{id}
  methods: GET
  controller: App\Controller\TodoController::getById

todo_create:
  path: api/todos
  controller: App\Controller\TodoController::create  
  methods: POST

todo_updateById :
  path: api/todos/{id}
  methods: PUT
  controller: App\Controller\TodoController::updateById

todo_toggleIsCompleted:
  path: api/todos/{id}
  methods: PATCH
  controller: App\Controller\TodoController::toggleIsCompleted

todo_removeById:
  path: api/todos/{id}
  methods: DELETE
  controller: App\Controller\TodoController::removeById
