user_get_all:
  path: api/users
  methods: GET
  controller: App\Controller\UserController::get_all

user_get_by_id:
  path: api/users/{id}
  methods: GET
  controller: App\Controller\UserController::get_by_id

user_create:
  path: api/users
  methods: POST
  controller: App\Controller\UserController::create

user_update_by_id:
  path: api/users/{id}  
  methods: PUT
  controller: App\Controller\UserController::update_by_id
