user_getAll:
  path: api/users
  methods: GET
  controller: App\Controller\UserController::getAll
  condition: "!request.query.has('numChars')"

user_getAllLongerThan:
  path: api/users{numChars?\d+\}
  methods: GET
  controller: App\Controller\UserController::getAllLongerThan
  defaults:
    numChars: 1
  condition: "request.query.has('numChars')"

user_getById:
  path: api/users/{id}
  methods: GET
  controller: App\Controller\UserController::getById

user_create:
  path: api/users
  methods: POST
  controller: App\Controller\UserController::create

user_updateById:
  path: api/users/{id}  
  methods: PUT
  controller: App\Controller\UserController::updateById

user_removeById:
  path: api/users/{id}  
  methods: DELETE
  controller: App\Controller\UserController::removeById
